name: test

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      # - run: pnpm run lint
      - run: pnpm run test
      # - run: pnpm codecov
